version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: recipe-server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: recipe-client
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server
