name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      VITE_API_ORIGIN: http://localhost:3000
      VITE_API_PATH: /api/v1/trpc
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
      DB_TYPE: ${{ secrets.DB_TYPE }}

    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: turing
          POSTGRES_PASSWORD: turing
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"
          cache: "npm"

      - name: Print environment variables
        run: printenv | grep -E 'DATABASE_URL|TOKEN_KEY|DB_TYPE'

      - name: Install dependencies
        run: npm ci

      - name: Type check server
        run: npm run typecheck -w=server

      - name: Test server (unit)
        run: npm run test -w=server

      - name: Type check client
        run: npm run typecheck -w=client

      - name: Lint server
        run: npm run lint -w=server

      - name: Lint client
        run: npm run lint -w=client

      - name: Test client (unit)
        run: npm run test:unit -w=client

      - name: Run server database migrations
        run: npm run migrate:latest -w=server

      - name: Test server
        run: npm run test -w=server

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start server for E2E tests
        run: npm run dev -w=server &

      - name: Build front end for E2E tests
        run: npm run build -w=client

      - name: Wait for server to startup
        uses: Jtalk/url-health-check-action@v4
        with:
          max-attempts: 5
          retry-delay: 5s
          url: ${{ env.VITE_API_ORIGIN }}/api/health

      - name: Test client E2E
        run: npm run test:e2e -w=client

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7
