name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      VITE_API_ORIGIN: http://localhost:3000
      VITE_API_PATH: /api/v1/trpc
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
      DB_TYPE: ${{ secrets.DB_TYPE }}

    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: turing
          POSTGRES_PASSWORD: turing
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"
          cache: "npm"

      - name: Print environment variables
        run: printenv | grep -E 'DATABASE_URL|TOKEN_KEY|DB_TYPE'

      - name: Install dependencies
        run: npm ci

      - name: Type check server
        run: npm run typecheck -w=server

      - name: Test server (unit)
        run: npm run test -w=server

      - name: Test server
        run: npm run test -w=server
